{
  "formatVersion": "1.1",
  "component": {
    "group": "com.camrin",
    "module": "email_validator",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "email_validator-1.0.aar",
          "url": "email_validator-1.0.aar",
          "size": 33775,
          "sha512": "b97029913e3bf3b873f7873e0272999c3eaa64456e665a3aaaec62a989b2efd3c38718d17b4007915a9d8d8f311dcd72f5b7052397ab64a0822bff014ad94afd",
          "sha256": "fd98a84633f008b5cc40d048e8596455e3933c88e80d6ed3ff621fc4ac05577e",
          "sha1": "9d0fc10c328976ea490764dd3e1c26f0df578e6f",
          "md5": "88c72efb2a7ef8097f12e9504e13d0af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "email_validator-1.0.aar",
          "url": "email_validator-1.0.aar",
          "size": 33775,
          "sha512": "b97029913e3bf3b873f7873e0272999c3eaa64456e665a3aaaec62a989b2efd3c38718d17b4007915a9d8d8f311dcd72f5b7052397ab64a0822bff014ad94afd",
          "sha256": "fd98a84633f008b5cc40d048e8596455e3933c88e80d6ed3ff621fc4ac05577e",
          "sha1": "9d0fc10c328976ea490764dd3e1c26f0df578e6f",
          "md5": "88c72efb2a7ef8097f12e9504e13d0af"
        }
      ]
    }
  ]
}
